### ISSUE TITLE
templates.js use with express-enrouten will cause a error

### ISSUE THREAD

**Issue by code-tinker** [benchpressjs/benchpressjs#32] opened 2015-03-18 11:24 UTC
i use templates.js with express-enrouten,
and it can't work.

```
TypeError: undefined is not a function
at replace (/root/web/website/node_modules/templates.js/lib/templates.js:167:38)
at replaceValue (/root/web/website/node_modules/templates.js/lib/templates.js:172:10)
at parseValue (/root/web/website/node_modules/templates.js/lib/templates.js:372:10)
at parse (/root/web/website/node_modules/templates.js/lib/templates.js:392:17)
at parse (/root/web/website/node_modules/templates.js/lib/templates.js:390:17)
at parseTemplate (/root/web/website/node_modules/templates.js/lib/templates.js:123:14)
at Object.templates.parse (/root/web/website/node_modules/templates.js/lib/templates.js:109:11)
at /root/web/website/node_modules/templates.js/lib/templates.js:157:30
at fs.js:336:14
at FSReqWrap.oncomplete (fs.js:99:15)
```

i print the options pass to templates.js:

```
{ settings: 
{ 'x-powered-by': false,
 etag: 'weak',
 'etag fn': [Function: wetag],
 env: 'development',
 'query parser': 'extended',
 'query parser fn': [Function],
 'subdomain offset': 2,
 'trust proxy': undefined,
 'trust proxy fn': [Function: trustNone],
 view: [Function: View],
 views: '/root/web/website/public/templates',
 'jsonp callback name': 'callback',
 'view cache': true,
 mountpath: '/',
 'view engine': 'tpl' },
enrouten: { routes: {}, path: [Function: path] },
_csrf: 'XTAuiXqtEtU3nbcKL5OClTI+PIFizNIo+BR28=',
user: { name: {} },
_locals: null,
cache: true }
```

**enrouten.routes.toString is undefined**

**Comment by julianlam** [comment] 2015-03-18 15:29
We've never tested templates.js against express-enrouten... can you let us know how your routes are defined in your routes index?

**Comment by lzhongzh** [comment] 2015-03-19 00:55
it seems always happen.
as long as you use the express-enrouten middleware, and start up the application it will cause the error.

my templates.js version is 0.1.29
express-enrouten version is 1.2.0
node version is v0.12.0

and the enrouten config is

    app.use(enrouten({
        index: 'routes/'
    }));

the routes/index \:

    controllers = require '../controllers'

    module.exports = (router) ->
        router.get '/', controllers.index

**Comment by psychobunny** [comment] 2015-03-19 00:58
Is this project publically available on github etc so I can have a look? Thanks

**Comment by lzhongzh** [comment] 2015-03-19 01:54
https://github.com/lzhongzh/templatesTest.git

npm start then visit the index you will see the problem~

Thanks

**Comment by lzhongzh** [comment] 2015-03-20 02:43
is there any conclusion?

**Comment by kamikaz1k** [comment] 2017-11-18 19:26
The issue is with `express-enrouten`, you can check the call [here]:(https://github.com/krakenjs/express-enrouten/blob/v1.x/lib/registry.js#L63)
`registry.routes = routes || Object.create(null);`

When `express-enrouten` is mounted, it makes this call which leads to creating an object without a `toString` method because that's what `Object.create(null)` does. See SO [here](https://stackoverflow.com/a/18640862/4765841).

A way to fix this might be to add a `toString` method inside of the `replace` function in benchpress. But I don't know what the full impact that would be.

```
function replace(string, regex, value) {
  if (value.toString == void 0) {
    value.toString = Object.prototype.toString;
  }
  return string.replace(regex, value.toString().replace(regexes.backReferenceFix, '$$$'));
}
```

As an aside, what might be a reason to return an object that extends (?) from null? Why not just use a `{}`...

**Comment by pitaj** [comment] 2017-11-18 19:44
Did you try this with Benchpress? 

I ask because it may or may not be fixed in Benchpress, I left it open because I couldn't be sure it was fixed or not.

**Comment by kamikaz1k** [comment] 2017-11-20 02:50
I used @code-tinker's demo repo: https://github.com/lzhongzh/templatesTest.git
Switching to benchpress didn't throw any error, but it also didn't do anything (I don't know how to use kraken/enrouten). I don't think there's a dependency on the `toString` method anymore so I'd be inclined to say it's not a benchpress problem anymore.

**Comment by pitaj** [comment] 2017-11-20 02:52
In that case I'm gonna close this. We can re-open if and when somebody has an issue.

**Closed by pitaj** 2017-11-20 02:52 UTC
Labels: needs confirmation
